export default function TermsPage() {
  return (
    <main className="mx-auto max-w-screen-sm p-4">
      <h1 className="text-lg font-semibold mb-3">Terms of Service</h1>
      <p className="text-sm text-slate-700">By using SriLankaLens.ai, you agree to read source articles via the original publishers. We do not claim ownership of external content. Summaries are generated by AI and may include errors; please consult sources.</p>
    </main>
  );
}

